
FROM node:18-alpine AS build
WORKDIR /usr/src/app

COPY frontend/package*.json ./
RUN npm install --legacy-peer-deps
COPY frontend/ .


RUN npm run build -- --configuration production 

FROM nginx:stable-alpine AS runtime

COPY --from=build /usr/src/app/dist/angular-15-crud /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
